- name: Deploy to EB
  uses: einaregilsson/beanstalk-deploy@v19
   with:
     aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
     aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
     application_name: Myinstapp2
     environment_name: Myinstapp2-env
     version_label: ${{ github.run_id }}
     region: us-east-1
     deployment_package: deployment.zip
